[[language]]
auto-format = true
name = "nix"
formatter = {command = "alejandra"}

[[language]]
language-servers = ["svelteserver", "tailwindcss-ls"]
name = "svelte"

[language-server.tailwindcss-ls]
args = ["--stdio"]
command = "tailwindcss-language-server"
