# See the full configuration reference: https://rioterm.com/docs/config

confirm-before-quit = false

[fonts]
size = 14
use-drawable-chars = false

[fonts.regular]
family = "IoskeleyMono Nerd Font"
style = "Regular"

[fonts.bold]
family = "IoskeleyMono Nerd Font"
style = "Bold"

[fonts.italic]
family = "IoskeleyMono Nerd Font"
style = "Italic"

[fonts.bold-italic]
family = "IoskeleyMono Nerd Font"
style = "Bold Italic"

[colors]
background = "#141218"
foreground = "#e6e0e9"

[window]
opacity = 1.0
opacity-cells = false
blur = false
