# See the full configuration reference: https://rioterm.com/docs/config

confirm-before-quit = false

[fonts]
size = 14
use-drawable-chars = true

[fonts.regular]
family = "FiraCode Nerd Font"
style = "Regular"

[fonts.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[fonts.italic]
family = "FiraCode Nerd Font"
style = "Regular"

[fonts.bold-italic]
family = "FiraCode Nerd Font"
style = "Bold"

[colors]
background = "#141218"
foreground = "#e6e0e9"

[window]
opacity = 1.0
opacity-cells = false
blur = false
