# See the full configuration reference: https://rioterm.com/docs/config

confirm-before-quit = false

[fonts]
size = 14
use-drawable-chars = true
symbol-map = [
  { start = "E000", end = "F8FF", font-family = "FiraCode Nerd Font Mono" },
  { start = "F0000", end = "FFFFD", font-family = "FiraCode Nerd Font Mono" },
]

[fonts.regular]
family = "FiraCode Nerd Font Mono"
style = "Regular"

[fonts.bold]
family = "FiraCode Nerd Font Mono"
style = "Bold"

[fonts.italic]
family = "FiraCode Nerd Font Mono"
style = "Regular"

[fonts.bold-italic]
family = "FiraCode Nerd Font Mono"
style = "Bold"

[window]
opacity = 0.75
opacity-cells = true
blur = true
