server_endpoint = "/run/user/1000/clipcat/grpc.sock"
finder = "custom"
preview_length = 80

[rofi]
line_length = 100
menu_length = 30
menu_prompt = "Clipcat"
extra_arguments = []

[dmenu]
line_length = 100
menu_length = 30
menu_prompt = "Clipcat"
extra_arguments = []

[choose]
line_length = 100
menu_length = 30
menu_prompt = "Clipcat"
extra_arguments = []

[custom_finder]
# dmenu here is a wrapper to anyrun with stdin plugin loaded
program = "dmenu"
args = []

[log]
emit_journald = true
emit_stdout = false
emit_stderr = false
level = "INFO"
