on:
  push:
    branches: [master]

jobs:
  build-pkg:
    name: Build Nix package
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: DeterminateSystems/determinate-nix-action@main
      - uses: "DeterminateSystems/flakehub-push@main"
        with:
          name: "Dreaming-Codes/nixos"
          rolling: true
          visibility: "public"
          include-output-paths: true
      - uses: DeterminateSystems/flakehub-cache-action@main
      - run: nix build .#nixosConfigurations.DreamingDesk.config.system.build.toplevel
